---
title: "bioc 202: Fundamentals of population genomics"
output:
  html_document:
    theme: flatly
---

#### Reid Brennan and Jennifer Nascimento Schulze
#### Summer 2024
#### GEOMAR

<br>

Welcome! This is a master's level course designed to give background and practical experience in population genomics. The goal is that you are able to analyze and interpret population genomic data by the end of the course. This will require gaining some practical skills in bioinformatic methods as well as knowledge of the biology to be able to interpret results.

The course will take place 8:30-12:00 from May 13-24 in room 5-3.228. See the [Schedule](https://rsbrennan.github.io/EvolutionaryGenomics_2024/schedule.html) for full details. Note that one day (May 14) we will meet in room 8A-002. 

We will spend the first half of the course learning methods and concepts via hands on tutorials and short lectures. During the second half you will analyze a dataset and present the results at the end of the course.

See the other pages on this site for more specific information. 

You can find cloudlab [here](https://lms.uni-kiel.de/auth/RepositoryEntry/5451644982/CourseNode/109531948798168). Remember that you need to sign in via OLAT.

