---
title: "Syllabus"
output:
  html_document:
    theme: flatly
---
  
# Fundamentals of population genomics - bioc-202
  
Instructors: 
  - Reid Brennan,rbrennan@geomar.de
  - Jenny Nascimento- Schulze, 

The course will take place 8:30-12:00 from May ??? in room ????. See the Schedule for full details.

Course website: rsbrennan.github.io/EvolutionaryGenomics_2024

### Course introduction
The goal of this course is to provide a theoretical and methodological foundation in population genomics. 
We’re at an exciting time as evolutionary biologists. It is now fairly easy to generate huge amounts of sequence data, i.e., genomics. However, the analysis and understanding of these data are not trivial. The approach in this course will be to focus on the basics of evolutionary principles and apply these basics to current genomics data. We will start with data processing and quality control of typical sequence data and then cover methods to detect including population structure and selection. You should leave with practical with skills in both bioinformatic methods (unix, bash, R) as well as an understanding of population genetics.

The first week we will work together through a [tutorial](https://rsbrennan.github.io/EvolutionaryGenomics_2024/tutorials.html) using a real dataset. The second week you will [analyze your own dataset.](https://rsbrennan.github.io/EvolutionaryGenomics_2024/project_overview.html)

For the entire course we will be using [cloudlab](https://cloudlab.rz.uni-kiel.de/) for our computing.

The students should leave this course with strong foundation and understanding of evolutionary genomics. Learning goals include:
- Fundamental principles in population genomics
- Techniques, type of data and analyses commonly used and how to apply them.
- Realized and potential contributions of these approaches in marine sciences. 

### Your main responsibilities:
- Showing up and participating
- Supporting each other and sharing your knowledge with your classmates
- Analyzing your independent project
- Presenting your results and analysis via 
  - a markdown document (turned in to Reid/Jenny)
  - a poster presentation

### Course website
Most resources, instructions, etc., will be hosted on the course website: rsbrennan.github.io/EvolutionaryGenomics_2024. There you can find the schedule, tutorials, lecture slides, and so on. Please check this resource regularly. 

### Grades
- Participation (20%), 
- Markdown/html document of your analysis (40%)
- Poster presentation of your results (40%)

### Schedule
Find the schedule on the [course website](https://rsbrennan.github.io/EvolutionaryGenomics_2024/schedule.html)
